# Generated by Django 4.2.13 on 2024-06-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='collaborator',
            new_name='staff',
        ),
    ]
