# Generated by Django 4.2.13 on 2024-06-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_collaborator_user_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='test', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
